# Generated by build/generate-r8-rules.sh - do not edit by hand; edit the script and re-run.
#
# Keep-rules for consuming Android applications that build with R8 (AndroidLinkTool=r8).
# See the .targets alongside for why .NET for Android needs these shipped explicitly.

# ---- upstream consumer rules (marketingcloudsdk-11.0.1.aar proguard.txt), shipped verbatim ----
# AltBeacon might not be added by customer
-dontwarn org.altbeacon.**
# Locations might not be added by customer
-dontwarn com.google.android.gms.location.**

# Salesforce SDK
-keep class com.salesforce.marketingcloud.** { *; }
-keep interface com.salesforce.marketingcloud.** { *; }
-keep enum com.salesforce.marketingcloud.** { *; }
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (pushfeaturemodule-2.0.1.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (pushmodelsmodule-1.0.3.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (inappmessagingfeaturemodule-1.0.1.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (inappmessagingmodelsmodule-1.0.1.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (common-1.0.1.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- legacy-crypto-1.0.3.aar ships no proguard.txt ----
# ---- curated: the JNI-only entry surface C# reaches (invisible to R8) ----

# The SDK entry points and configuration builders are constructed and called only from C#.
-keep class com.salesforce.marketingcloud.MarketingCloudSdk { *; }
-keep class com.salesforce.marketingcloud.MarketingCloudConfig { *; }
-keep class com.salesforce.marketingcloud.MarketingCloudConfig$Builder { *; }
-keep class com.salesforce.marketingcloud.InitializationStatus { *; }

# The public feature surfaces driven from C# on instances the SDK hands out. Keeping the
# interfaces keeps their implementations on live classes.
-keep class com.salesforce.marketingcloud.notifications.** { *; }
-keep class com.salesforce.marketingcloud.registration.** { *; }
-keep class com.salesforce.marketingcloud.messages.** { *; }
